name: CR1 - Extract IPS

on:
  workflow_run:
    workflows: ["Sort"]  # Name of the primary workflow
    types:
      - completed  # Trigger only when the primary workflow is completed
    branches: [main] 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Cleanup & Load IR Configs
      run: |
        > geo/config.txt
        cp sort/IR.txt geo/config.txt
        
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        > geo/iplist.txt
        python -m pip install --upgrade pip
        pip install ipaddress requests

    - name: Run IP Extractor
      run: python geo/extract.py

    - name: Check for Changes
      id: changesex
      run: |
            git diff --quiet && echo 'No changes' || echo '::set-output name=changed::true'   
    - name: Commit changes
      if: steps.changesex.outputs.changed == 'true'     
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add geo/ex.txt
        timestamp=$(TZ='Asia/Tehran' date)
        git commit -m "✅List updated ${timestamp}"
        git push
